package com.drools.example
import java.util.ArrayList

import com.drools.example.controllers.QuestionViewController
import com.drools.example.UserAnswer
import com.drools.example.Question
import com.drools.example.Car
import java.util.ArrayList
import java.util.Arrays
import org.kie.api.task.model.User



rule "Init"
    when
    then
    System.out.println("Init rule fired - first question added");

    ArrayList<UserAnswer> answers = new ArrayList<>();
    answers.add(new UserAnswer("Reliability and convenience bore me"));
    answers.add(new UserAnswer("I guess I'm making some kind of statement about something?"));
    answers.add(new UserAnswer("New cars have no soul"));
    answers.add(new UserAnswer("I prefer the style"));
    answers.add(new UserAnswer("Love speed, hate safety"));

    insert(new Question("Why do you want a classic?", answers, new ArrayList<Car>()));
end


rule "Show question with possible answers"
    when
        q : Question();
        guiController : QuestionViewController();
    then
        guiController.updateQuestion(q);
end


// Reliability and convenience bore me - branch 1/5

rule "Why do you want a classic? - Reliability and convenience bore me"
    when
        q : Question(content == "Why do you want a classic?");
        a : UserAnswer(content == "Reliability and convenience bore me");
    then
        ArrayList<UserAnswer> answers = new ArrayList<>();
        answers.add(new UserAnswer("I want to know how cars work"));
        answers.add(new UserAnswer("I'm erotically drawn to tow trucks and freeway shoulders"));
        retract(a)
        retract(q)
        insert(new Question("Oh yeah? Why's that?", answers, new ArrayList<Car>()));
end

rule "Oh yeah? Why's that? - I'm erotically drawn to tow trucks and freeway shoulders"
    when
        q : Question(content == "Oh yeah? Why's that?");
        a : UserAnswer(content == "I'm erotically drawn to tow trucks and freeway shoulders");
    then
        ArrayList<UserAnswer> answers = new ArrayList<>();
        answers.add(new UserAnswer("Also really lovely"));
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Lotus Elan"));
        retract(a)
        retract(q)
        insert(new Question("Ok. Should it be pretty quick?", answers, cars));
end

rule "Ok. Should it be pretty quick? - Also really lovely"
    when
        q : Question(content == "Ok. Should it be pretty quick?");
        a : UserAnswer(content == "Also really lovely");
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Alfa Romeo Giulia Super"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Oh yeah? Why's that? - I want to know how cars work"
    when
        q : Question(content == "Oh yeah? Why's that?");
        a : UserAnswer(content == "I want to know how cars work");
    then
        ArrayList<UserAnswer> answers = new ArrayList<>();
        answers.add(new UserAnswer("Sounds good"));
        answers.add(new UserAnswer("More archaic"));
        answers.add(new UserAnswer("Not that archaic"));
        retract(a)
        retract(q)
        insert(new Question("So, something really simple?", answers, new ArrayList<Car>()));
end

rule "So, something really simple? - Sounds good"
    when
        q : Question(content == "So, something really simple?");
        a : UserAnswer(content == "Sounds good");
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Citroen 2CV"));
        cars.add(new Car("VW Thing"));
        cars.add(new Car("Willys Jeep"));
        cars.add(new Car("Honda Civic"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "So, something really simple? - More archaic"
    when
        q : Question(content.equals("So, something really simple?"));
        a : UserAnswer(content.equals("More archaic"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Ford model T"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "So, something really simple? - Not that archaic"
    when
        q : Question(content.equals("So, something really simple?"));
        a : UserAnswer(content.equals("Not that archaic"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Ford model A"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

// I guess I'm making some kind of statement about something? - branch 2/5

rule "Why do you want a classic? - I guess I'm making some kind of statement about something?"
    when
        q : Question(content.equals("Why do you want a classic?"));
        a : UserAnswer(content.equals("I guess I'm making some kind of statement about something?"));
    then
        ArrayList<UserAnswer> answers = new ArrayList<>();
        answers.add(new UserAnswer("I'm really rich but like to pretend I'm still a hippie"));
        answers.add(new UserAnswer("The mothership left me in Paris"));
        answers.add(new UserAnswer("I run an NYC-themed diner in Las Vegas"));
        answers.add(new UserAnswer("I live dangerously and Nader can suck it"));
        answers.add(new UserAnswer("I will only drive vehicles with two distinct luggage areas"));
        answers.add(new UserAnswer("I'm a kook. An american kook."));
        answers.add(new UserAnswer("I take driving seriously and have the gloves to prove it"));
        answers.add(new UserAnswer("My wallet is on a chain"));
        answers.add(new UserAnswer("I'm a refugee from an alternate future with zeppelins and shit"));
        answers.add(new UserAnswer("I like being part of a massive automotive subculture"));
        answers.add(new UserAnswer("I hate people knowing what i drive"));
        answers.add(new UserAnswer("I kinda wanted a motorcycle, but i have no balance"));
        retract(a)
        retract(q)
        insert(new Question("Great, what kind of statement?", answers, new ArrayList<Car>()));
end

rule "Great, what kind of statement? - I'm really rich but like to pretend I'm still a hippie"
when
    q : Question(content.equals("Great, what kind of statement?"));
    a : UserAnswer(content.equals("I'm really rich but like to pretend I'm still a hippie"));
then
    ArrayList<Car> cars = new ArrayList<>();
    cars.add(new Car("VW type 2 microbus"));
    retract(a)
    retract(q)
    insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Great, what kind of statement? - The mothership left me in Paris"
    when
        q : Question(content.equals("Great, what kind of statement?"));
        a : UserAnswer(content.equals("The mothership left me in Paris"));
   then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Citroen SM"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Great, what kind of statement? - I run an NYC-themed diner in Las Vegas"
    when
        q : Question(content.equals("Great, what kind of statement?"));
        a : UserAnswer(content.equals("I run an NYC-themed diner in Las Vegas"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Checker Marathon"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Great, what kind of statement? - I live dangerously and Nader can suck it"
    when
        q : Question(content.equals("Great, what kind of statement?"));
        a : UserAnswer(content.equals("I live dangerously and Nader can suck it"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Chevy Corvair"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Great, what kind of statement? - I will only drive vehicles with two distinct luggage areas"
    when
        q : Question(content.equals("Great, what kind of statement?"));
        a : UserAnswer(content.equals("I will only drive vehicles with two distinct luggage areas"));
    then
        ArrayList<UserAnswer> answers = new ArrayList<>();
        answers.add(new UserAnswer("No"));
        answers.add(new UserAnswer("Yes"));
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("VW type III"));
        retract(a)
        retract(q)
    insert(new Question("Something faster?", answers, cars));
end

rule "Something faster? - No"
    when
        q : Question(content.equals("Something faster?"));
        a : UserAnswer(content.equals("No"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("VW type III"));
        retract(a)
        retract(q)
    insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Something faster? - Yes"
    when
        q : Question(content.equals("Something faster?"));
        a : UserAnswer(content.equals("Yes"));
    then
        ArrayList<UserAnswer> answers = new ArrayList<>();
        answers.add(new UserAnswer("No"));
        answers.add(new UserAnswer("Yes"));
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Porsche 914"));
        retract(a)
        retract(q)
    insert(new Question("Even faster?", answers, cars));
end

rule "Even faster? - No"
    when
        q : Question(content.equals("Even faster?"));
        a : UserAnswer(content.equals("No"));
    then
        ArrayList<Car> cars = new ArrayList<>();
                cars.add(new Car("Porsche 914"));
        retract(a)
        retract(q)
    insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Even faster? - Yes"
    when
        q : Question(content.equals("Even faster?"));
        a : UserAnswer(content.equals("Yes"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("De Tomaso Mangusta"));
        retract(a)
        retract(q)
    insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Great, what kind of statement? - I'm a kook. An american kook."
    when
        q : Question(content.equals("Great, what kind of statement?"));
        a : UserAnswer(content.equals("I'm a kook. An american kook."));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("AMC AMX"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Great, what kind of statement? - I take driving seriously and have the gloves to prove it"
    when
        q : Question(content.equals("Great, what kind of statement?"));
        a : UserAnswer(content.equals("I take driving seriously and have the gloves to prove it"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Porsche 911"));
    cars.add(new Car("BMW E30"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Great, what kind of statement? - My wallet is on a chain"
    when
        q : Question(content.equals("Great, what kind of statement?"));
        a : UserAnswer(content.equals("My wallet is on a chain"));
    then
        ArrayList<UserAnswer> answers = new ArrayList<>();
        answers.add(new UserAnswer("Yes"));
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Ford Falcon"));
        cars.add(new Car("Plymouth Valiant"));
        retract(a)
        retract(q)
        insert(new Question("Not for style, I'm tired of losing it", answers, cars));
end

rule "Not for style, I'm tired of losing it - Yes"
    when
        q : Question(content.equals("Not for style, I'm tired of losing it"));
        a : UserAnswer(content.equals("Yes"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Rambler American"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Great, what kind of statement? - I'm a refugee from an alternate future with zeppelins and shit"
    when
        q : Question(content.equals("Great, what kind of statement?"));
        a : UserAnswer(content.equals("I'm a refugee from an alternate future with zeppelins and shit"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Tatra T87"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Great, what kind of statement? - I like being part of a massive automotive subculture"
    when
        q : Question(content.equals("Great, what kind of statement?"));
        a : UserAnswer(content.equals("I like being part of a massive automotive subculture"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("VW Beetle"));
        cars.add(new Car("BMW 2002"));
        cars.add(new Car("MGB"));
        cars.add(new Car("Datsun 240Z"));
        cars.add(new Car("Volvo 240"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Great, what kind of statement? - I hate people knowing what i drive"
    when
        q : Question(content.equals("Great, what kind of statement?"));
        a : UserAnswer(content.equals("I hate people knowing what i drive"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Sterling 825"));
        cars.add(new Car("Mitsubishi Starion"));
        cars.add(new Car("Isuzu I-Mark"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Great, what kind of statement? - I kinda wanted a motorcycle, but i have no balance"
    when
        q : Question(content.equals("Great, what kind of statement?"));
        a : UserAnswer(content.equals("I kinda wanted a motorcycle, but i have no balance"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Lotus 7"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

// New cars have no soul - branch 3/5

rule "Why do you want a classic? - New cars have no soul"
    when
        q : Question(content == "Why do you want a classic?");
        a : UserAnswer(content == "New cars have no soul");
    then
        ArrayList<UserAnswer> answers = new ArrayList<>();
        answers.add(new UserAnswer("Easy: ability to drive off a pier into an estuary"));
        answers.add(new UserAnswer("Synonym for weird"));
        answers.add(new UserAnswer("Technically novel"));
        answers.add(new UserAnswer("Soul means the car had an honest job, like a cop or cabbie"));
        answers.add(new UserAnswer("It means riding in it is like sitting on a sofa"));
        answers.add(new UserAnswer("It means the car is often starring in movies"));
        answers.add(new UserAnswer("It could mean pure evil?"));
        answers.add(new UserAnswer("Soul is the spirits of 43 dead clowns haunting the car"));
        answers.add(new UserAnswer("Soul is the ability to go a million miles with SU carbs and Lucas electrics"));
        retract(a)
        retract(q)
        insert(new Question("What does soul mean to you?", answers, new ArrayList<Car>()));
end

rule "What does soul mean to you? - Easy: ability to drive off a pier into an estuary"
    when
        q : Question(content.equals("What does soul mean to you?"));
        a : UserAnswer(content.equals("Easy: ability to drive off a pier into an estuary"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Amphicar"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "What does soul mean to you? - Synonym for weird"
    when
        q : Question(content.equals("What does soul mean to you?"));
        a : UserAnswer(content.equals("Synonym for weird"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("BMW Isetta"));
        cars.add(new Car("Messerschmidt Kabinroller"));
        cars.add(new Car("Subaru 360"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "What does soul mean to you? - Technically novel"
    when
        q : Question(content.equals("What does soul mean to you?"));
        a : UserAnswer(content.equals("Technically novel"));
    then
        ArrayList<UserAnswer> answers = new ArrayList<>();
        answers.add(new UserAnswer("Instead of pistons, some metal hamantaschen"));
        answers.add(new UserAnswer("Can burn cooking oil"));
        answers.add(new UserAnswer("Engine in the wrong place (maybe colled by wrong stuff)"));
        answers.add(new UserAnswer("They thought they were building a plane"));
        retract(a)
        retract(q)
        insert(new Question("Like what?", answers, new ArrayList<Car>()));
end

rule "Like what? - Instead of pistons, some metal hamantaschen"
    when
        q : Question(content.equals("Like what?"));
        a : UserAnswer(content.equals("Instead of pistons, some metal hamantaschen"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Mazdra RX-7"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Like what? - Can burn cooking oil"
    when
        q : Question(content.equals("Like what?"));
        a : UserAnswer(content.equals("Can burn cooking oil"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Mercedes Benz 300TD"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Like what? - Engine in the wrong place (maybe colled by wrong stuff)"
    when
        q : Question(content.equals("Like what?"));
        a : UserAnswer(content.equals("Engine in the wrong place (maybe colled by wrong stuff)"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Porsche 912"));
        cars.add(new Car("Renault Alpine"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "Like what? - They thought they were building a plane"
    when
        q : Question(content.equals("Like what?"));
        a : UserAnswer(content.equals("They thought they were building a plane"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Saab 96"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "What does soul mean to you? - Soul means the car had an honest job, like a cop or cabbie"
    when
        q : Question(content.equals("What does soul mean to you?"));
        a : UserAnswer(content.equals("Soul means the car had an honest job, like a cop or cabbie"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Ford Crown Vic"));
        cars.add(new Car("Dodge Monaco"));
        cars.add(new Car("Chevy Caprice"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "What does soul mean to you? - It means riding in it is like sitting on a sofa"
    when
        q : Question(content.equals("What does soul mean to you?"));
        a : UserAnswer(content.equals("It means riding in it is like sitting on a sofa"));
    then
        ArrayList<UserAnswer> answers = new ArrayList<>();
        answers.add(new UserAnswer("Yes"));
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Lincoln Town Car"));
        retract(a)
        retract(q)
        insert(new Question("A huge, fast FWD sofa?", answers, cars));
end

rule "A huge, fast FWD sofa? - Yes"
    when
        q : Question(content.equals("A huge, fast FWD sofa?"));
        a : UserAnswer(content.equals("Yes"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Olds Tornado"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "What does soul mean to you? - It means the car is often starring in movies"
    when
        q : Question(content.equals("What does soul mean to you?"));
        a : UserAnswer(content.equals("It means the car is often starring in movies"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("VW Beetle"));
        cars.add(new Car("Delorean DMC-12"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "What does soul mean to you? - It could mean pure evil?"
    when
        q : Question(content.equals("What does soul mean to you?"));
        a : UserAnswer(content.equals("It could mean pure evil?"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Plymouth Fury"));
        cars.add(new Car("Buick GNX"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "What does soul mean to you? - Soul is the spirits of 43 dead clowns haunting the car"
    when
        q : Question(content.equals("What does soul mean to you?"));
        a : UserAnswer(content.equals("Soul is the spirits of 43 dead clowns haunting the car"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Nash Metropolitan"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

rule "What does soul mean to you? - Soul is the ability to go a million miles with SU carbs and Lucas electrics"
    when
        q : Question(content.equals("What does soul mean to you?"));
        a : UserAnswer(content.equals("Soul is the ability to go a million miles with SU carbs and Lucas electrics"));
    then
        ArrayList<Car> cars = new ArrayList<>();
        cars.add(new Car("Volvo P1800"));
        retract(a)
        retract(q)
        insert(new Question("", new ArrayList<UserAnswer>(), cars));
end

// I prefer the style - branch 4/5
